version: '3.8'

services:
  ddd-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ddd-api-container
    ports:
      - "8080:8080"
    restart: always